### ISSUE TITLE
Verify rpc communication: client <-> places_server <-> airport_server

### ISSUE THREAD

**Issue by galaxyonfire** [Arjunica/hw4#1]
Implement simple client and servers to verify that each entity can properly talk to each other.

**Comment by QuinnWass** [comment]
![Screenshot from 2020-10-12 16-14-06](https://user-images.githubusercontent.com/13488199/95798256-4d8b2080-0ca6-11eb-8852-02bb638893a5.png)

I am able to pass through the code through all levels!
