### ISSUE TITLE
Improve Client Expected Input Documentation

### ISSUE THREAD

**Issue by QuinnWass** [Arjunica/hw4#31]
Currently we do not make it clear whether the state or city comes first

**Comment by Arjunica** [comment]
Do you mean within the calls? The assignment doc makes it clear that when running client: "./exe host city state". Thanks

**Comment by QuinnWass** [comment]
Yes when providing an err msg 

	char *host;
	char *cityName;
	char *stateAbrv;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cityName = argv[2];
	stateAbrv = argv[3];`

**Comment by Arjunica** [comment]
gotcha. Ya i'll fix that in my branch. Thanks!
