### ISSUE TITLE
I cannot verify functionality of Places

### ISSUE THREAD

**Issue by Arjunica** [Arjunica/hw4#40]
I do not think that airport server is being called. I made the error code positive. and can't hit debug print line
<img width="789" alt="Screen Shot 2020-10-21 at 8 50 28 PM" src="https://user-images.githubusercontent.com/8902297/96822640-651d8400-13df-11eb-9273-42dcda5b24c6.png">

Maybe we need to relook at Places server standing up code

**Comment by Arjunica** [comment]
look at the branch am/hotfixPlacesStatus

**Comment by QuinnWass** [comment]
Works fine for me. You need to reload the server if you change something in it.

**Comment by Arjunica** [comment]
Interesting. I always kill both -> make clean - > make then run both
servers then client. I'll try to see where I'm going wrong. Can you try
just printing the long-lat of the city you search for

Thanks,
--Arjun

**Comment by QuinnWass** [comment]
Verified works via zoom
